services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - .:/app  # Mounts the current directory into the container
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db  
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - app_network
  
  pgadmin:  
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Change this to my email later
      PGADMIN_DEFAULT_PASSWORD: admin  # Change this to a secure password later
    ports:
      - "5050:80"  # Access pgAdmin at http://localhost:5050
    depends_on:
      - db
    networks:
      - app_network

volumes:
  pgdata:  

networks:
  app_network:
    driver: bridge