"""Added S3 URL column

Revision ID: 7e77091cdffb
Revises: 9b6765687e92
Create Date: 2025-02-18 16:07:03.280993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e77091cdffb'
down_revision: Union[str, None] = '9b6765687e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('s3_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 's3_url')
    # ### end Alembic commands ###
